ci/azure-test-all.yml
tests/futures.rs

Related https://github.com/tokio-rs/tokio/pull/1367

Add test for futures feature to CI

---

Cargo.toml
src/future/mod.rs

Unblock https://github.com/tokio-rs/tokio/issues/1423

Update futures-preview to 0.3.0-alpha.18

---

src/rt/execution.rs
src/rt/vv.rs
tests/causal_cell.rs

[WIP] Test false positive causal cell race

---

src/sync/condvar.rs

This does not provide an accurate implementation of `wait_timeout` but
allows unblocking use cases that require using this function.

condvar: stub out wait_timeout

---

README.md

I assume this is the intended content.
@carllerche please confirm it's what you meant.

Fix presumed typo in README.md

---

src/lazy_static.rs

Looks like a copy/paste error.

Fix module comment for lazy_static

---

tests/thread_api.rs

Apparently I forgot to check this in on the prior PR (#175)

thread: add tests for some thread APIs

---

tests/spec.rs

https://en.cppreference.com/w/cpp/atomic/memory_order

Add C++ memory ordering spec tests

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/lib.rs

generator 0.7 requires Rust 1.51: https://github.com/tokio-rs/loom/pull/203#issuecomment-812500571

Bump MSRV to 1.51

---

src/sync/rwlock.rs

std rwlock provides it: https://doc.rust-lang.org/nightly/std/sync/struct.RwLock.html#impl-From%3CT%3E

Add From implementation to RwLock

---

src/sync/atomic/int.rs

Fix docs of atomic integers

---

src/sync/atomic/bool.rs
src/sync/atomic/int.rs
src/sync/atomic/ptr.rs

std atomic types provide them: https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicU8.html#impl-From%3Cu8%3E
Closes #194

Add From implementation to atomic types

---

Cargo.toml

Update generator to 0.7

---

src/sync/atomic/int.rs
tests/atomic_int.rs

Includes:
* `fetch_nand`
* `fetch_min`
* `fetch_max`

Add several methods to Atomic integer types

---

src/sync/arc.rs

Adds Arc::pin. Close https://github.com/tokio-rs/loom/issues/223

Arc::pin added

---

.gitignore
src/sync/arc.rs

`increment_strong_count`/`decrement_strong_count` added. Copy/paste from https://doc.rust-lang.org/src/alloc/sync.rs.html#1003

Arc counter manipulations

---

Cargo.toml
src/lib.rs
src/model.rs
src/rt/alloc.rs
src/rt/arc.rs
src/rt/atomic.rs
src/rt/condvar.rs
src/rt/execution.rs
src/rt/mod.rs
src/rt/mutex.rs
src/rt/notify.rs
src/rt/object.rs
src/thread.rs

This PR was picked up after #91 and updated with the latest changes from master !

Improve logging #2

---

src/sync/arc.rs

Arc::Inner now have "C" layout

---

src/rt/mutex.rs
tests/deadlock.rs

Don't attempt to cleanup Mutex when threads are deadlocked

---

Cargo.toml

I guess this unblocks https://github.com/tokio-rs/tokio/pull/4227
Closes #237

Update tracing-subscriber to 0.3

---

src/sync/mpsc.rs

I'm not familiar enough with loom to judge if this is the right way to do it, but at least it seems to be working in my tests.

Implement try_recv function for mpsc Receiver.

---

src/alloc.rs
src/lazy_static.rs
src/sync/atomic/mod.rs
src/sync/mod.rs
src/thread.rs

See https://github.com/tokio-rs/tokio/pull/2874 for the motivation.

Use #[doc(no_inline)] on re-exports

---

Cargo.toml
src/lib.rs

The latest version is 0.7.
https://github.com/tokio-rs/loom/blob/b8d0cd89ac6a88de61ae1dccd90a1a780f53c012/src/lib.rs#L117-L118

Update loom version in docs

---

Cargo.toml

Update generator to 0.8.1

---

Cargo.toml

Drop unused tracing-attributes and its proc-macro-related dependencies.

Disable default features of tracing

---

Cargo.toml
src/rt/execution.rs

Upgrade to 2021 edition 
