src/sync/arc.rs, src/sync/mod.rs
This is needed when `CausalCell` instances are accessed on drop.
=> Provide Arc implementation

src/sync/arc.rs
This PR adds the following APIs to `loom::sync::Arc<T>`:
- `Arc::ptr_eq`
- `Arc::strong_count`
- `Default`
- `From<T>`
It also adds some basic docs (the current docs just say "TODO").
Unresolved questions:
- Should we add support for weak refcounting?
- Should we add some tests for this Arc?
- How do we implement the methods that std uses fences for (`try_unwrap` etc.)?
=> Flesh out the std::sync::Arc mock implementation

src/rt/scheduler/mod.rs
=> Remove cfg_attr(..., path)

src/rt/execution.rs, src/rt/vv.rs, src/sync/causal/cell.rs, tests/causal_cell.rs
+ `CausalCell` now also keeps track of closure of immutable access times.
+ Mutable access now panics on concurrent immutable access(es).
+ Immutable access now correctly panics on concurrent mutable access.
+ Add `VersionVector::copy_from`.
=> Add `CausalCell` concurrent immut+mut access race detection

src/future/mod.rs, src/rt/thread.rs, tests/mutex.rs
Only unpark the future's executor thread if it parked because the future
returned `Poll::Pending`. Otherwise, we accidentally wake up the
thread even though it actually parked from e.g. waiting on a locked
mutex. Instead, since we have set the `notified` flag, the future will
immediately poll again after it finally returns `Poll::Pending`.
+ Add `pending` flag to `Thread` to track futures returning `Poll::Pending`.
I suspect it might make sense to eventually add a `Waker` object or something
instead of tracking these flags everywhere.
=> Fix `Waker` so it only unparks if `Future` returns `Poll::Pending`

src/sync/atomic/atomic.rs, src/sync/atomic/bool.rs, src/sync/atomic/int.rs, src/sync/atomic/ptr.rs
Hey! Just tried using `loom`, and hit the issue of loom's atomics not being exactly std's atomics -- here is a PR to try and reduce this by implementing `Default` for atomics.
=> Implement Default for atomics

src/sync/mod.rs, src/sync/notify.rs
This type is useful for mocking out primitives when writing tests.
=> Expose Notify

src/rt/execution.rs, src/rt/object.rs, src/sync/atomic/atomic.rs, src/sync/notify.rs
Instead of requiring the user to conditionally bound by `Send`, make
Loom types should implement Send / Sync as appropriate.
=> Make mocked types Sync / Send

src/lib.rs, src/rt/thread.rs, src/thread.rs, tests/thread_local.rs
When running a test that uses `loom`'s mock threads, all the mock
threads in the test are actually run on the same OS thread. This means
that code which uses thread local storage will not behave the same
inside of a `loom` test — every `loom` "thread" will actually see the
same version of the thread-local.
This branch adds a mock implementation of the Rust standard library's
`std::thread::LocalKey` type to `loom::thread`, and a mock version of
the `thread_local!` macro that expands to a mock `loom` `LocalKey`.
This is implemented by adding a hash map of `LocalKey`static addresses
to  `Box<dyn Any>`s in the `loom::rt::thread::Thread` type, and having
the mock `LocalKey` type access the current thread from the runtime, and
use its address to index the current thread's map. The boxed `Any` …
=> Add mock thread locals

src/rt/atomic.rs, src/sync/causal/cell.rs, src/sync/causal/mod.rs, src/sync/mod.rs
`CausalCell` provides a structure that verifies that the accessing
thread has synchronized appropriately to be able to to access the cell.
However, there are algorithms where a thread must read
**optimistically** from a causal cell before it knows that it can
perform the read. In this case, the thread reads the bytes from the cell
to a temporary location then performs the necessary atomic operation to
verify access.
To model this, a new API is added to CausalCell that allows deferring
the causality check to a later time. `with_deferred` returns a
`CausalCheck` that can be used at a later time to assert the previous
access was correct.
=> Provide an API to defer causality checks

src/rt/vv.rs, src/sync/causal/cell.rs, tests/causal_cell.rs
The initial version of the deferred causal cell check simply stored the
result of the check in a value enabling the caller to defer the panic.
However, the CausalCell was immediately and unconditionally applied.
In cases where the CausalCell read was attempted then aborted, this
caused concurrent writes to fail due to a perceived conflict.
This patch updates the CausalCell to track state for each outstanding
deferred check. This way, the CausalCell state is not updated until it
is known that the access will be committed.
=> Fix deferred causal cell check

src/future/atomic_waker.rs, src/lib.rs, src/rt/mutex.rs, tests/futures.rs
Add a `yield_now` when `register` wakes the given task due to the state
being locked. This behavior results in a spin lock, so it must be
annotated as such.
=> fix AtomicWaker

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Unblock https://github.com/tokio-rs/tokio/pull/1610
This may cause a version conflict in crates that currently depend on tokio-0.2.0-alpha. This is because [loom pins version of futures-util-preview](https://github.com/carllerche/loom/blob/e352ded9887ab0bcc9f868b08ec3bab12b81216e/Cargo.toml#L40) and [tokio does not pin version of loom](https://github.com/tokio-rs/tokio/blob/7c341f45e03c26187b7146c5a10f404de86cca9c/tokio-sync/Cargo.toml#L36). (This may also have happened in previous releases.)
However, both futures-preview and tokio are pre-releases and loom's futures support is an optional feature... and [optional features do not necessarily have the same stability as crate itself.](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#major-change-going-from-stable-to-n …
=> Prepare v0.2.8 release

src/rt/arc.rs, src/rt/mod.rs, src/rt/thread.rs, src/sync/arc.rs, src/sync/mutex.rs, src/thread.rs
Collecting up a bunch of fixes.
This includes a fix to the thread local implementation. All "hooks" must be called from outside of the `rt::execution` closure.
=> Misc fixes

src/rt/mutex.rs, src/sync/mutex.rs
Loom's `Mutex` lacks a `try_lock` method like `std::sync::Mutex` has. In
order to simulate all code that uses `std`'s mutex, we should add this.
This branch adds `try_lock` to `loom::sync::Mutex`. This was easy to
implement using the existing `try_acquire_lock` on `rt::Mutex`, which is
no longer feature flagged with the "futures" feature.
Closes #82
=> Add `loom::sync::Mutex::try_lock`

src/rt/atomic.rs
Consider the following program (`x` is a shared variable, the `SeqCst`
ordering is assumed):
* thread 0 (main): store 0 in x
* thread 1: store 1 in x
* thread 2: store 2 in x
* thread 0 (main): wait for thread 1; wait for thread 2; load x
Without this change, concurrent writes are considered independent, so
Loom fails to explore `store 2` followed by `store 1`.
For orderings other than `SeqCst`, this is likely to introduce
redundant dependencies, resulting in more thread interleavings being
explored than necessary.
=> Change `last_dependent_accesses` for atomics

src/lib.rs
The loom implementation fo thread-locals appears to work most of the
time. However, in some cases, when running models in release model,
thread-local values appear to vanish.
This patch fixes the bug. The cause of the bug is using `const` instead
of `static` for defining the thread-local key type. By using `const`,
there is no guarantee of a single instance of the key. It is surprising
that, to date, the thread-local implementation appeared to mostly work.
=> fix thread-local bug

src/rt/arc.rs, src/rt/atomic.rs, src/rt/condvar.rs, src/rt/execution.rs, src/rt/mutex.rs, src/rt/notify.rs, src/rt/object.rs
As per https://github.com/tokio-rs/loom/pull/94#discussion_r342879131, it is not really necessary to store load and store accesses for `Atomic` separately, so the method returning last dependent accesses for an operation can simply return an `Option`. This simplifies the code and gives a nice performance benefit by getting rid of iterator boxing.
=> Don't use iterators to get last dependent accesses

src/rt/access.rs, src/rt/arc.rs, src/rt/atomic.rs, src/rt/condvar.rs, src/rt/execution.rs, src/rt/mutex.rs, src/rt/notify.rs, src/rt/object.rs, src/rt/thread.rs, src/rt/vv.rs
A couple of small changes to reduce memory allocations:
* switch `last_dependent_accesses` to internal iteration to avoid boxing iterators
* reuse VersionVecs of last accesses
As a benchmark, with these changes running time of tokio-executor loom tests went down from 21.0s (with loom 0.2.12) to 16.6s on my machine.
=> Some performance improvements

src/rt/scheduler.rs
Loom uses its own thread implementation using generators. Unfortunately,
this means that thread-locals do not work when using a loom model as all
code runs on a single physical thread. Loom provides a mocked
thread_local API to work around this.
However, when using `async / await`, `std` uses an internal thread-local
to track the waker as it passes through the async block. If loom
preempts at this point, the context gets shared with the wrong thread,
resulting in SEGV.
This patch fixes this by wrapping the loom context switch with an async
block and polling the async block w/ a noop waker. Doing this forces the
real waker to be moved out of thread-local storage and to the stack,
which is persisted across the loom context switch.
=> fixes Loom when using async/await

src/rt/thread.rs, tests/causal_cell.rs
The previous SeqCst is incorrectly implemented. SeqCst is identical to
AcqRel except that it provides a sequental modification order. The
previous imlementation provided global happens-before, which is too
strong.
As a stop-gap, this PR disables SeqCst support, which means it will fail
to validate algorithms that correctly rely on SeqCst guarantees.
However, it should prevent validationg buggy code.
=> Relax how SeqCst is modelled

Cargo.toml, src/model.rs, src/rt/arc.rs, src/rt/backtrace.rs, src/rt/execution.rs, src/rt/mod.rs
An initial pass at tracking backtraces during execution. Currently, only
`Arc::new` is tracked, but now that infrastructure is added, tracking
additional events should be easier.
Capturing a backtrace is a an expensive event. The failure case should
be isolated before capturing backtraces.
=> basic backtrace tracking

src/rt/cell.rs, tests/unsafe_cell.rs
The thread version vector was not bumped on `UnsafeCell` access. This
caused synchronizations that happened immediately **before** the access
to prevent loom from detecting invalid `UnsafeCell` access.
=> fix `UnsafeCell` bug

src/rt/arc.rs, src/rt/atomic.rs, src/rt/mod.rs, src/rt/mpsc.rs, src/rt/object.rs, src/sync/arc.rs, src/sync/barrier.rs, src/sync/mod.rs, src/sync/mpsc.rs, src/sync/rwlock.rs, tests/mpsc.rs
Adds Loom mocks for `std::sync::mpsc`. Also, adds unimplemented stubs for `std::sync::barrier` that the code that depends on them could be at least compiled.
**Note:** This PR includes the changes from #88, so you probably want to merge it first. **cc**: @pop
=> Add support for mpsc channels

src/lazy_static.rs, src/lib.rs, src/model.rs, src/rt/execution.rs, src/rt/lazy_static.rs, src/rt/mod.rs, tests/atomic.rs
This adds the `lazy_static!` macro from the `lazy_static` crate. We need
to re-implement it both since it establishes causality (through its use
of `Once`), and because the state needs to be cleared on every
execution. This implementation does that.
One unfortunate downside of this implementation is that it is inherently
unsafe. Specifically, in the context of loom, statics are, well, not
static. And yet the API of `lazy_static!` is such that it gives out
`'static` references. We _cannot_ safely give out `'static` refs into
statics that we clear on every execution.
One option here is to leak every static we allocate. The code would then
be safe (since the references would indeed be `'static`), but it would
mean we leak _all_ statics for _every_ execution, no matter whether the
user needs …
=> Add lazy_static macro

src/lazy_static.rs, src/rt/lazy_static.rs, tests/atomic.rs
The real lazy_static uses a lock to avoid races in initialization. We
don't implement that lock yet, so our initialization can race. If we do,
we should not crash like we did before.
Fixes #126.
=> Don't crash on lazy_static init race

src/rt/object.rs, src/rt/rwlock.rs, src/sync/rwlock.rs, tests/rwlock.rs
Fixes a RwLock bug where the reader and writer threads were not
correctly enabled / disabled in order to respect the RwLock guarantees.
This resulted in `write()` locks being granted while there are
outstanding readers.
cc @vakaras @pop
=> Fix RwLock implementation

src/sync/condvar.rs, src/sync/mutex.rs, src/sync/rwlock.rs
I noticed the `loom` versions of `Mutex` and `RwLock` does not implement `Default`. This PR adds that, so they become more similar.
=> Implement Default for Mutex, RwLock and Condvar

CHANGELOG.md, Cargo.toml, src/lib.rs, src/rt/notify.rs
Fixed
- An example in the README failing to compile (#132)
Changed
- Updated `scoped-tls` to 1.0.0 (#153)
Added
- `Send` and `Sync` impls for `JoinHandle` (#145)
- `Default` impls for `Mutex`, `RwLock`, and `Condvar` (#138)
=> prepare to release 0.3.5

README.md, src/lib.rs
Hello :crab: , this PR makes minor typo fixes to README & docs.
Thank you for reviewing this PR :+1:
=> minor typo fixes to README & docs

src/rt/mod.rs, src/rt/thread.rs, src/thread.rs
This implements Thread and ThreadId, with the exception of the park() and
unpark() APIs.
=> Partially implement thread::{Thread,ThreadId}

src/hint.rs, src/lib.rs
`std::sync::atomic::spin_loop_hint` is deprecated, so loom should provide the non-deprecated replacement. It just calls the deprecated version though.
I provided `unreachable_unchecked` too, even though it's not *exactly* `loom`'s wheelhouse, but it could help catch some UB, and lets users potentially reduce the amount of `cfg` special-casing they need.
=> Add a `loom::hint` module containing mocked versions of `spin_loop` and `unreachable_unchecked`

src/sync/atomic/atomic.rs, src/sync/atomic/bool.rs, src/sync/atomic/int.rs, src/sync/atomic/ptr.rs, tests/atomic_int.rs
`fetch_update` is useful for implementing CAS loops with less code.
=> Add fetch_update to atomics

CHANGELOG.md, Cargo.toml
Note: The `Cargo.toml` had already been changed in a previous commit.
- Bump MSRV to 1.51 (#205)
- Add `From` implementation to `Mutex` (#131)
- Add `From` implementation to `RwLock` (#209)
- Add `From` implementation to atomic types (#210)
- Add `fetch_update` to atomics (#212)
- Move `futures-util` to `dev-dependencies` (#208)
- Update `generator` to 0.7 (#203)
=> chore: prepare v0.5.0

CHANGELOG.md, Cargo.toml
- Add several methods to atomic integer types (#217)
=> Prepare v0.5.1

src/cell/unsafe_cell.rs
`std`'s `UnsafeCell`﻿ doesn't have `T: Sized` requirement, so I don't see why the `loom` version should be different.
=> Remove implicit `T: Sized` requirement from `UnsafeCell`

README.md, src/rt/atomic.rs, src/rt/synchronize.rs, src/rt/thread.rs, tests/atomic.rs, tests/fence.rs, tests/litmus.rs
This PR implements `Release`, `AcqRel`, and `SeqCst` fences. 
* `Release` fence can be implemented by recording the `causality` of the thread, which is joined with the later stores (see `released: VersionVec`).
* `AcqRel` fence is `Acquire` fence + `Release` fence.
* `SeqCst` fence uses the old implementation of `SeqCst`, which was removed in #108 for being too strong. However, that implementation is the correct if `SeqCst` is used only for fences. Please see https://github.com/tokio-rs/loom/issues/180#issuecomment-903264839 for more information.
Partially addresses #180
cc: @jeehoonkang @wvwwvwwv
=> Implement `Release`, `AcqRel`, and `SeqCst` fences

src/sync/mutex.rs, src/sync/rwlock.rs, tests/mutex.rs, tests/rwlock.rs
These are pretty easy to implement as they both move the lock itself, so
there's no concurrency to think about.
=> Implement `Mutex::into_inner` and `RwLock::into_inner`

src/cell/cell.rs, src/cell/mod.rs
It isn't too rare to use `Cell<T>` instead of `UnsafeCell<T>` if `T` is `Copy`. It also is way more compatible with the stdlib API. Wasn't sure what to do for tests here.
=> Add a loom::cell::Cell, which provides a basic wrapper of the loom UnsafeCell

src/sync/arc.rs
This PR adds `Arc::as_ptr(&Self)`.
=> Arc::as_ptr

src/alloc.rs, src/cell/mod.rs, src/future/mod.rs, src/hint.rs, src/model.rs, src/rt/access.rs, src/rt/atomic.rs, src/rt/cell.rs, src/rt/location.rs, src/rt/mod.rs, src/rt/mpsc.rs, src/rt/object.rs, src/rt/path.rs, src/rt/rwlock.rs, src/rt/scheduler.rs, src/rt/thread.rs, src/rt/vv.rs, src/sync/arc.rs, src/sync/atomic/bool.rs, src/sync/atomic/int.rs, src/sync/atomic/mod.rs, src/sync/atomic/ptr.rs, src/sync/notify.rs, src/thread.rs, tests/deadlock.rs, tests/fence.rs, tests/rwlock_regression1.rs, tests/thread_local.rs
This branch fixes a big pile of clippy lints. These are mostly not
particularly important, but they were kinda bugging me, so I thought it
was nice to fix them.
I've tried to separate out each individual lint category into separate
commits, with notes in the commit message as necessary. Most of these
changes are completely trivial, but there are a few that might be worth
actually reviewing in detail. Therefore, each commit can be considered
individually, and if there are any cases where we don't like Clippy's
suggestions, I can back out those commits and add `#[allow(...)]`
attributes instead.
In particular, `clippy` suggested adding
`Default` implementations for a few types. This seems pretty harmless,
but (unlike the rest of this PR) it *is* an actual API change, so if
that's unwanted, …
=> fix a bunch of annoying clippy lints

src/thread.rs
Currently, `loom`'s mock version of `std::thread` does not provide
mocked `std::thread::park` or `std::thread::Thread::unpark` APIs. It
would be nice to be able to use `loom` to test implementations of
synchronization primitives, and other code which uses `thread::park` and
`Thread::unpark`.
Fortunately, the `loom::rt` internals already contain the necessary
primitives to provide simulated versions of these APIs --- they're used
internally in the implementation of the mocked `Condvar` and `Notify`
types. This branch adds APIs for simulating `thread::park` and
`Thread::unpark`.
Closes #133
=> thread: Add mock versions of `thread::park` and `Thread::unpark`

CHANGELOG.md, Cargo.toml
- thread: Add mock versions of `thread::park` and `Thread::unpark` (#240)
- Don't attempt to clean up Mutex when threads are deadlocked (#236)
- Update tracing-subscriber to 0.3 (#238)
=> chore: prepare loom 0.5.3

src/rt/scheduler.rs
A mistake we sometimes make when working on [a large code base that uses Loom for testing](https://www.amazon.science/publications/using-lightweight-formal-methods-to-validate-a-key-value-storage-node-in-amazon-s3) is messing up our conditional imports, such that either a non-Loom-controlled `std::thread` is constructed or a Loom synchronization primitive is accessed from outside the context of a Loom model.
Here's a simple example distilled from one such mistake I made just now:
```rust
#[test]
fn thing() {
loom::model(|| {
let lock = Arc::new(Mutex::new(0));
let thd = {
let lock = lock.clone();
// oops, wrong `thread`, not controlled by loom
std::thread::spawn(move || {
*lock.lock().unwrap() += 1;
})
};
thd.join().unwrap();
let lock = …
```
=> Improve error message when execution `STATE` is unavailable

src/alloc.rs, src/cell/unsafe_cell.rs, src/rt/scheduler.rs
It looks like rustc 1.57.0 got slightly better at finding unused struct
fields and started emitting warnings for fields that are never read. In
all the cases that emitted a warning in loom, the unused field is a drop
guard which is held to indicate the lifetime of something, and is never
read from.
I've added leading `_`s to these fields' names to suppress the warnings.
This should fix the build.
Additionally, I fixed a clippy "needless borrow" warning.
=> chore: fix unused field warnings 

CHANGELOG.md, Cargo.toml
- cell: Add `ConstPtr` and `MutPtr` RAII guards to `UnsafeCell` (#219)
- Improve error message when execution state is unavailable (such as
when running outside of `loom::model`) (#242)
=> chore: prepare to release 0.5.4

src/rt/path.rs, tests/double_panic_in_drop.rs
Loom will panic if the maximum number of branches is exceeded. If a
type's `Drop` impl performs a branch (for example, a `MutexGuard` or
`Arc`, or a user-defined type that performs atomic operations in its
`Drop` impl), we will hit the assertion a _second_ time, resulting in a
double panic. This sucks, because it makes these test failures much
harder to debug.
This branch fixes the issue by changing the assertion checking path
length to also check if the current thread is panicking. If we're
already panicking, we don't make the assertion, to avoid causing a
double panic. I've added a test that reproduces this double panic, as
well.
I've also fixed a typo in the assertion message. :)
=> fix double panic when exceeding the branch limit in `Drop`

src/cell/unsafe_cell.rs
=> Allow using `{Mut,Const}Ptr::{deref,with}` when the pointee is `!Sized`

src/rt/mod.rs, src/rt/thread.rs, tests/thread_api.rs
If `std::thread::Thread::unpark` is called _prior_ to a call to
`std::thread::park`, the `park` call will return immediately,
"consuming" the previous unpark. Per [the documentation][1]:
> The `unpark` method on a `Thread` atomically makes the token available
> if it wasn’t already. Because the token is initially absent, `unpark`
> followed by `park` will result in the second call returning
> immediately.
Loom's version of this API does not have this behavior. It appears that
`unpark` only notifies a thread if it is currently `park`ed, and does
not influence the next call to `park`.
The following test demonstrates this:
```rust
#[test]
fn park_unpark_loom() {
loom::model(|| {
loom::thread::current().unpark();
loom::thread::park();
println!("it did not deadlock");
});
}
#[test]
fn …
```
=> thread: fix semantics of `thread::park` after `Thread::unpark`

src/sync/atomic/bool.rs, src/sync/atomic/int.rs, src/sync/atomic/ptr.rs
std's atomic types have the same in-memory representation as the underlying type.
https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicUsize.html
> This type has the same in-memory representation as the underlying integer type, usize.
loom's atomic types have a different in-memory representation than the underlying type. ([it](https://github.com/tokio-rs/loom/blob/3ebe3d1ee16b1c5f09ee3d46a3a621ebee04d6f0/src/rt/atomic.rs#L72-L73) is an [index](https://github.com/tokio-rs/loom/blob/3ebe3d1ee16b1c5f09ee3d46a3a621ebee04d6f0/src/rt/object.rs#L39-L41) in the store)
=> Add note about in-memory representation of atomic types

src/sync/atomic/ptr.rs
I think the root issue here is one of that tasks related to [rust#26925](https://github.com/rust-lang/rust/issues/26925). `AtomicPtr<T>` can still have a debug implementation for when `T` is not itself `Debug`.
This was brought up from doing work on [haphazard#32](https://github.com/jonhoo/haphazard/pull/32).
=> Change derive(Debug) AtomicPtr to an explicit impl for all T, not just T: Derive.

src/future/atomic_waker.rs, src/future/mod.rs, src/rt/arc.rs, src/rt/atomic.rs, src/rt/condvar.rs, src/rt/mod.rs, src/rt/mpsc.rs, src/rt/mutex.rs, src/rt/notify.rs, src/rt/object.rs, src/rt/rwlock.rs, src/rt/thread.rs, src/sync/arc.rs, src/sync/condvar.rs, src/sync/mpsc.rs, src/sync/mutex.rs, src/sync/notify.rs, src/sync/rwlock.rs, src/thread.rs
This PR is mostly just mechanical. It adds `#[track_caller]` and gets the location in the public API and plumbs it through. This helps debug deadlocks:
```
thread 'runtime::tests::loom_pool::group_a::pool_multi_spawn' panicked at 'deadlock; threads = [(Id(0), Blocked(Location(Some(Location { file: "tokio/src/runtime/tests/loom_oneshot.rs", line: 45, col: 31 })))), (Id(1), Blocked(Location(Some(Location { file: "tokio/src/park/thread.rs", line: 112, col: 30 })))), (Id(2), Blocked(Location(Some(Location { file: "tokio/src/runtime/thread_pool/park.rs", line: 206, col: 30 }))))]'
```
The output is pretty bad, but it is definitely helpful :)
=> track locations

src/rt/execution.rs, src/sync/arc.rs
This is an attempt to resolve #85
=> Remove (implicit) `T: Sized` bound from `Arc`

src/model.rs, src/rt/thread.rs
This branch makes a few minor improvements to how Loom uses `tracing` to
generate `LOOM_LOG` output:
* Added `with_test_writer` to the `tracing` subscriber. This allows logs
written by Loom to be captured by `libtest`. This way, running Loom
tests with `--show-output` will print the `LOOM_LOG` output from each
test under that test's heading. Similarly, this allows libtest to
capture Loom log output by default, and print the output back for
failed tests.
* Updated to the latest `tracing-subscriber` version. This gets us
slightly nicer-looking formatting but is otherwise not that important.
* Added `tracing` spans for each simulated Loom thread. Now, when we
switch threads, we also switch to that thread's corresponding
`tracing` span. This way, all output in the log is annotated with the …
=> improve `LOOM_LOG` tracing

src/alloc.rs, src/rt/alloc.rs, src/rt/arc.rs, src/rt/mod.rs, src/rt/mpsc.rs, src/rt/object.rs, src/sync/arc.rs, src/sync/mpsc.rs
Currently, loom's mock `Arc` will track the source code location where
the `Arc` was created. This is useful for diagnosing problems, but it
isn't always *enough* to make the output easy to understand. 
In particular, `LOOM_LOG=trace` will indicate where the `Arc` was
created, and will log ref count operations on that `Arc`. The creation
location is useful , but ref count operations aren't associated with a
location --- so a user reading the log cannot determine _where_ the
`Arc`'s reference count was incremented or decremented from. This makes
tracking leaks difficult.
Additionally, in the `LOOM_LOG` output, each `Arc` instance is
identified by its `Ref` (an index in the store of loom object states).
This permits tracking an individual `Arc`'s refcount lifecycle in the
logs. However, …
=> add additional location tracking to `Arc`, `alloc`, and `mpsc`

src/model.rs, src/rt/thread.rs
This commit adds a `tracing` span with the current model's iteration
that's entered every time an iteration begins. This should make it much
easier to distinguish individual iterations in the `LOOM_LOG` output.
This was supposed to be part of #266 (and I discussed it in the PR
description for that branch) but I forgot to push this commit. Whoops.
=> add a `tracing` span for the current model's iteration

.github/workflows/release.yml
Currently, Loom publishes a GitHub release when publishing a new version
of the crate. However, this is an extra step in the release process which
is easy to accidentally forget: the current release is v0.5.4, but the
last GitHub release was v0.5.2.
This branch introduces automatic publishing of GitHub releases for
release tags, using taiki-e/create-gh-release-action. GitHub releases
are automatically created when a tag matching the regex `v[0-9]+.*` is
pushed to the `master` branch on the origin repository. The release
notes are automatically populated from CHANGELOG.md.
This should make it much easier to remember all the manual steps to
release a new version of loom --- we only need to push a tag, not push
a tag *and* create a release.
=> ci: automatically publish GitHub releases

CHANGELOG.md, Cargo.toml
- sync: Add `Arc::from_std` without `T: Sized` bound (#226)
- sync: Implement `Debug` for `AtomicPtr` for all `T` (#255)
- logs: Add location tracking for threads and atomic operations (#258)
- logs: Add additional location tracking to `Arc`, `alloc`, and `mpsc`
(#265)
- logs: Improve `tracing` configuration for `LOOM_LOG` (#266)
- logs: Add a span for the current model's iteration (#267)
- Add note about in-memory representation of atomic types (#253)
- Document `LOOM_LOG` syntax (#257)
- Fix double panic when exceeding the branch limit in `Drop` (#245)
- cell: Allow using `{Mut,Const}Ptr::{deref,with}` when the pointee is
`!Sized` (#247)
- thread: Fix semantics of `thread::park` after `Thread::unpark` (#250)
=> chore: prepare loom v0.5.5

src/alloc.rs, src/thread.rs
PR #151 added a CI job to try and build the documentation, failing on
RustDoc errors. It turned out there was a handful of broken links, so
that job is now failing. 
I meant to fix this as part of #151 but accidentally automerged it
before fixing the docs, since automerge wasn't configured to require the
docs build job to pass. Whoops.
=> docs: fix broken rustdoc links

CHANGELOG.md, Cargo.toml
- cell: add `UnsafeCell::into_inner` for parity with `std` (#272)
- sync: re-enable `Arc::strong_count` (#172)
- sync: implement `Arc::try_unwrap` (#262)
- sync: add `mpsc::Receiver::try_recv` (#262)
- show feature flags in docs (#151)
- fix broken RustDoc links (#273)
=> chore: prepare to release v0.5.6

.github/workflows/release.yml
Same as https://github.com/tokio-rs/loom/pull/264, but for release.yml that didn't exist when that PR was created.
=> Update actions/checkout action to v3 in release.yml

.github/workflows/ci.yml, Cargo.toml
Increase the minimum bound on the `tracing-subscriber` dependency in order to make `cargo +nightly update -Z minimal-versions && cargo check` work on this crate. See https://github.com/tokio-rs/tracing/pull/1890
I also added to CI to have it check the minimal versions. Do you like it this way? It's a bunch of duplication. But I felt it made sense to check the minimal versions with all the same tasks as the normal stable test.
=> Upgrade tracing subscriber and check minimum dependency versions in CI

.github/workflows/ci.yml
Since dependencies changed their MSRV in a minor update, loom currently depends on `scoped-tls 1.0.1`, which has MSRV 1.59, making the minrust job fail.
=> Bump MSRV to 1.59

.github/workflows/ci.yml, Cargo.toml
We depend indirectly on `regex-syntax v0.7.1`, which has MSRV 1.60.0.
=> Bump MSRV to 1.60.0

src/rt/mod.rs, src/rt/rwlock.rs, src/rt/scheduler.rs, src/thread.rs, tests/thread_api.rs
Make `loom::thread::Builder::stack_size` not a no-op. This is done by spawning scheduler threads later such that the requested stack size can be applied then.
Fixes #309
=> Support setting model thread stack size

src/model.rs, src/rt/mod.rs
Tokio needs 5 threads to run loom tests now.
Five threads ought to be enough for anybody.
=> Increase max threads to 5

src/rt/mod.rs, src/rt/scheduler.rs, src/rt/thread.rs
This avoids forcing the generator to abort, which is not thread-safe.
=> ensure fn passed to generator completes

src/sync/arc.rs
These traits are necessary to use the Arc in places that expect AsRef and Borrow.
=> Implement AsRef and Borrow for Arc

src/sync/atomic/int.rs
doc_comment hack is no longer needed since MSRV has increased.
=> Use #[doc = concat!()] in atomic integer docs

src/sync/atomic/bool.rs, src/sync/atomic/int.rs, src/sync/atomic/ptr.rs
This implements Atomic*::into_inner using unsync_load, which has the same synchronization properties (AFAIK).
=> Add Atomic*::into_inner

src/sync/mutex.rs, src/sync/rwlock.rs
Add the standard library get_mut() method to Mutex and RwLock. This provides mutable access without locking for callers who already hold a &mut Mutex or &mut RwLock.
=> Add get_mut() to Mutex and RwLock

.github/workflows/ci.yml, Cargo.toml, src/lib.rs
As I was reading the docs, I noticed this typo and I just had to fix it.
=> Bump MSRV to 1.65

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml
- Update actions/checkout action to v4 
- Run CI on a regular basis (weekly)
- Remove no longer needed argument for cargo fmt
- Use cargo-hack's --rust-version flag for minrust job
This respects rust-version field in Cargo.toml, so it removes the need to manage MSRV in both the CI file and Cargo.toml.
=> Update CI config

src/sync/mutex.rs
`std` supports this so it would be nice if loom did too. The only changes needed to do it is just adding `?Sized` where applicable.
=> Allow `Mutex` to work with `?Sized` types

src/lib.rs
In order to let the `loom::lazy_static` macro work in contexts that are `#[no_std]`, use `marker::PhantomData` from `core` instead of `std`.
=> Use core instead of std in lazy_static! macro

src/rt/thread.rs
This fixes a compile failure due to the latest 1.77 changes.
=> Fix dead code warning

src/cell/cell.rs
Thanks for loom! I don't have sufficient context to know if there is a reason for this absence, but I ran into this difference between std::cell::Cell and loom::cell::Cell and it seemed easy enough to fix
=> feat: add loom::cell::Cell::into_inner

src/lib.rs
Currently, the `checkpoint` feature is required when using checkpoint files for debugging. I think it would be better to add this in the debugging doc examples.
=> Add `checkpoint` feature flag in the docs example

src/hint.rs
There’s a minor typo in a doc link in hint.rs.
=> Fix doc link typo in hint.rs

Cargo.toml, src/rt/object.rs, src/thread.rs
```
error: package `generator v0.8.3` cannot be built because it requires rustc 1.77 or newer, while the currently active rustc version is 1.65.0
```
https://github.com/tokio-rs/loom/actions/runs/10867411903/job/30156136540#step:4:60
Depend on https://github.com/Xudong-Huang/generator-rs/pull/68
=> Bump MSRV to 1.73

Cargo.toml, src/future/mod.rs
Depend on #364.
`std::pin::pin!` macro has been stabilized in Rust 1.68.
=> Use std::pin::pin! macro instead of pin-utils

src/sync/atomic/int.rs, src/sync/atomic/mod.rs
`AtomicU64` and `AtomicI64` are defined only if `target_pointer_width = 64`
https://github.com/tokio-rs/loom/blob/3ef62e2011cb3b3baf76251f42b8c6c1a12d555d/src/sync/atomic/int.rs#L193-L197
But they are exported for all targets
https://github.com/tokio-rs/loom/blob/3ef62e2011cb3b3baf76251f42b8c6c1a12d555d/src/sync/atomic/mod.rs#L10-L12
=> Fix build error on not 64 bit arch

src/sync/notify.rs
`Notify` is limited to one thread at a time, but this isn't documented.
(I'm not sure why this limitation exists, but I'd be curious to know)
=> Document Notify limitation
